title: Privatkopiera
url: https://stefansundin.github.io
baseurl: /privatkopiera
description: Privatkopiera enklare med detta tillägg.
author: Stefan Sundin
extension_id: jhjhnecocacdbhlkjgpdacoibidhmgdf
extension_name: privatkopiera

# posts
permalink: /news/:year-:month-:day-:title.html

# build
plugins:
- jekyll-github-metadata
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
future: true
