name: 游 Buggrapport
description: Rapportera en bugg
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Innan du skickar in buggrapporten
      description: 'Se till att du:'
      options:
        - label: Har kollat om det [redan finns en buggrapport](https://github.com/stefansundin/privatkopiera/issues) om det h칛r.
          required: true
        - label: Har kollat om det [redan finns en diskussionstr친d](https://github.com/stefansundin/privatkopiera/discussions) om det h칛r.
          required: true
        - label: T칛nkt efter om det h칛r kanske passar b칛ttre som [en diskussionstr친d](https://github.com/stefansundin/privatkopiera/discussions).
          required: true

  - type: input
    attributes:
      label: L칛nk till video med problem
      description: Om den h칛r rapporten inte har n친got att g칬ra med en specific tj칛nst s친 kan du skippa det h칛r f칛ltet.
      placeholder: https://...

  - type: textarea
    attributes:
      label: Beskriv buggen
      placeholder: Jag har problem med ...
    validations:
      required: true
